[package]
name = "lyutmc"
version = "0.1.0"
authors = ["Elliot Dewhurst <elliot@dewhurst.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx-hal = "=0.9.0"
winit = "0.28.6"
gfx-backend-vulkan = "=0.9.0"